version: '3'

services:
  app:
    container_name: sixthree_moneybook
    image: sixthree_moneybook:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    env_file:
      - ./backend/.env

